version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/chat_application?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=chat_application
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

networks:
  springmysql-net: